In [3]:
import numpy as np

In [2]:
#creation og numpy arrary
x = np.array([1,2,3,4,5])
print(x)
print(type(x)) #ndarray


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# shape and size
print(x.size)# total no. of elements
print(x.shape) #dimension wise elements
print(x.ndim) #num of dimension

5
(5,)
1


In [4]:
x2d = np.array([[1,2,3],[4,5,6,]])
print(x2d)
#shape and size
print(x2d.size)
print(x2d.shape)
print(x2d.ndim)

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [5]:
x25 = np.random.randint(1,100,(5,4))
print(x25)

[[80 87 34  7]
 [39  7  6 29]
 [70 38 34  1]
 [23 44 17 65]
 [76 92 69 15]]


In [6]:
xseq1 = np.arange(1,101,4)
print("1D matrix")
print(xseq1)

print(xseq1.size)

print(xseq1.reshape(5,5))
print('2D matrix')

1D matrix
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
25
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]
2D matrix


In [4]:
xseq2= np.linspace(1,100,50)
print(xseq2)
print(xseq2.size)
print(xseq2.reshape(10,5))


[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
50
[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327  43.42857143  45.44897959  47.46938776  49.4897959

In [ ]:
np.ones((5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

- indexing and slicing
- boolean filter
- maths and stars
- methods

In [ ]:
x25

array([[95,  9, 40, 53],
       [48,  6,  6, 14],
       [74, 64, 53, 78],
       [52, 73, 42, 55],
       [61, 15, 49, 41]])

In [ ]:
#first row
print(x25[0])

[95  9 40 53]


In [ ]:
#last row
print(x25[-1])

[61 15 49 41]


In [ ]:
print(x25[0,1]) # same as print(x25[0][1])

9


In [ ]:
#1st column
print(x25[:,0])
#2nd
print(x25[:,1])
#last
print(x25[:,-1])

[95 48 74 52 61]
[ 9  6 64 73 15]
[53 14 78 55 41]


In [ ]:
#column 0 and 1 index
print(x25[:,[0,1,2]])
#same
print(x25[:,:3])

[[95  9 40]
 [48  6  6]
 [74 64 53]
 [52 73 42]
 [61 15 49]]
[[95  9 40]
 [48  6  6]
 [74 64 53]
 [52 73 42]
 [61 15 49]]


In [ ]:
#boolean filter
x25

array([[95,  9, 40, 53],
       [48,  6,  6, 14],
       [74, 64, 53, 78],
       [52, 73, 42, 55],
       [61, 15, 49, 41]])

In [ ]:
# filtering data without numpy boolean filter
for i in x25:
    for j in i:
        if j <= 20:
            print(j)

9
6
6
14
15


In [ ]:
x25 <= 20 # boolean filer

array([[False,  True, False, False],
       [False,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [ ]:
x25[ x25 <= 20]

array([ 9,  6,  6, 14, 15])

In [ ]:
x25 [ x25 >= 20]

array([95, 40, 53, 48, 74, 64, 53, 78, 52, 73, 42, 55, 61, 49, 41])

In [ ]:
[(x25 > 20) & (x25 < 70)]

[array([[False, False,  True,  True],
        [ True, False, False, False],
        [False,  True,  True, False],
        [ True, False,  True,  True],
        [ True, False,  True,  True]])]

In [ ]:
np.append(x25, [1,2,3,4,5])

array([95,  9, 40, 53, 48,  6,  6, 14, 74, 64, 53, 78, 52, 73, 42, 55, 61,
       15, 49, 41,  1,  2,  3,  4,  5])

In [ ]:
np.append(x25,np.array([[1,2,3,4]]), axis=0)

array([[95,  9, 40, 53],
       [48,  6,  6, 14],
       [74, 64, 53, 78],
       [52, 73, 42, 55],
       [61, 15, 49, 41],
       [ 1,  2,  3,  4]])

In [ ]:
a = np.random.randint(1,100,(2,3))
print(a)
b = np.random.randint(1,100,(3,2))
print(b)

[[23  2 51]
 [52 68 90]]
[[34 39]
 [ 1 24]
 [88 77]]


In [ ]:
a.T # same as transpose

array([[23, 52],
       [ 2, 68],
       [51, 90]])

In [ ]:
print(np.hstack((a,b.T)))

[[23  2 51 34  1 88]
 [52 68 90 39 24 77]]


In [ ]:
print(np.vstack((a,b.T)))

[[23  2 51]
 [52 68 90]
 [34  1 88]
 [39 24 77]]


In [8]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x)
print(y)

[[7 9 3]
 [3 2 5]
 [8 7 4]]
[[3 8 5]
 [9 7 7]
 [1 9 7]]


In [11]:
print(x+y)
print('add')  #for gap
print(x-y)
print('sub')
print(x * y)
print('multiplication')
print(x / y)
print('div')
print(x % y)

[[10 17  8]
 [12  9 12]
 [ 9 16 11]]
add
[[ 4  1 -2]
 [-6 -5 -2]
 [ 7 -2 -3]]
sub
[[21 72 15]
 [27 14 35]
 [ 8 63 28]]
multiplication
[[2.33333333 1.125      0.6       ]
 [0.33333333 0.28571429 0.71428571]
 [8.         0.77777778 0.57142857]]
div
[[1 1 3]
 [3 2 5]
 [0 7 4]]


In [12]:
print(x.dot(y)) #mat multiplication
print()


[[105 146 119]
 [ 32  83  64]
 [ 91 149 117]]



In [13]:
x.sum() # sum of all value

48

In [14]:
x.sum(axis=0) # row wise sum

array([18, 18, 12])

In [15]:
x.sum(axis=1) # col wise sum

array([19, 10, 19])

In [21]:
print(x.mean()) #all
print(x.mean(axis=0)) # row
print(x.mean(axis=1)) #col

5.333333333333333
[6. 6. 4.]
[6.33333333 3.33333333 6.33333333]


In [23]:
print(x.max()) # max value
print(x.min()) # min vlue
print(x.argmax())  # index of max value
print(x.argmin()) # index of min value
#print(x.flatten[4]) # accessing the index value given by argmax()

9
2
1
4


In [24]:
np.median(x) # some function are called using np ,if not available

5.0